name: Build and Publish to IPFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'
    outputs:
      cid: ${{ steps.merklize.outputs.cid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - run: npm install -g @web3-storage/w3cli ipfs-car

      - name: Build project
        run: npm run build

      - name: Merkelize Build
        id: merklize
        run: |
          CID=$(npx ipfs-car pack out --no-wrap --output build.car --silent | tail -n 1)
          echo "cid=$CID" >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-car
          path: build.car

  publish-to-ipfs:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output-car

      - run: w3 space add ${{ secrets.STORACHA_PROOF }}
        env:
          W3_PRINCIPAL: ${{ secrets.STORACHA_KEY }}

      - run: w3 up --car build.car
        env:
          W3_PRINCIPAL: ${{ secrets.STORACHA_KEY }}

      # - name: Upload to IPFS
      #   uses: web3-storage/add-to-web3@v3
      #   id: web3storage
      #   with:
      #     path_to_add: 'out'
      #     secret_key: ${{ secrets.STORACHA_KEY }}
      #     proof: ${{ secrets.STORACHA_PROOF }}
      #     wrap: false

      - name: Update commit status
        uses: actions/github-script@v7
        with:
          script: |
            const cid = '${{ needs.build.outputs.cid }}';
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              target_url: `https://w3s.link/ipfs/${cid}`,
              description: `CID: ${cid}`,
              context: 'IPFS Preview'
            });

      - name: Find Comment to update
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '🚀 Building'

      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🚀 Build Preview on IPFS ready

            🔏 CID: `${{ needs.build.outputs.cid }}`
            [Preview Deployment](https://w3s.link/ipfs/${{ needs.build.outputs.cid }})
            [Service Worker Gateway Preview](https://inbrowser.link/ipfs/${{ needs.build.outputs.cid }})
          edit-mode: replace
