name: Build and Deploy to IPFS

# Explicitly declare permissions
permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Add concurrency to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ipfs-deploy.yml
    with:
      node-version: '20'
      kubo-version: '0.32.1'
      build-command: 'npm run build'
      build-output-dir: 'out'
    secrets:
      STORACHA_KEY: ${{ secrets.STORACHA_KEY }}
      STORACHA_PROOF: ${{ secrets.STORACHA_PROOF }}
      FILEBASE_SECRET_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
      FILEBASE_ACCESS_KEY: ${{ secrets.FILEBASE_ACCESS_KEY }}
